### ISSUE TITLE
log问题

### ISSUE THREAD

**Issue by BlessingCR** [houbb/resubmit#3]
能不能有配置把这几个log去掉或者设置为debug级别
[Cache] 开始清理过期数据
[Cache] 结束清理过期数据
设置 cache 信息, key: 05A0FF03B2F109E3F13090B666E39144, ttl: 5000
[Cache] 移除 key: 05A0FF03B2F109E3F13090B666E39144
Param is empty, return empty

**Comment by BlessingCR** [comment]
谢谢大哥，最好时spring可配置级别那种

**Comment by houbb** [comment]
抱歉，刚看到这个。我来改一下，调整为 debug 级别。

**Comment by houbb** [comment]
最新的 v1.1.0 已调整为 debug 级别。

```xml
<dependency>
    <group>com.github.houbb</group>
    <artifact>resubmit-spring</artifact>
    <version>1.1.0</version>
</dependency>
```

PS: 也可以指定包，修改三方框架的日志级别。
